{% set name = "kedro" %}
{% set version = "0.18.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro-{{ version }}.tar.gz
  sha256: 5bd995dc710507427097488200f9f40ac8fb5085bec415ae6dd2335a53ffbf49

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kedro = kedro.framework.cli:main

requirements:
  host:
    - pip
    - python >=3.7,<3.11
  run:
    - anyconfig >=0.10.0,<1.0.0
    - attrs >=21.3,<24.0
    - python-build >=0.7.0,<1.0.0
    - cachetools >=5.3,<6.0
    - click >=7.0,<9.0
    - cookiecutter >=2.1.1,<3.0
    - dynaconf >=3.1.2,<4.0
    - fsspec >=2021.4,<2024.1
    - gitpython >=3.0,<4.0
    - importlib_metadata >=3.6,<7.0.0
    - importlib-metadata >=3.6,<7.0.0
    - importlib_resources >=1.3,<7.0.0
    - jmespath >=0.9.5,<2.0.0  # 1.0.1
    - more-itertools >8.14.0,<10.0
    - omegaconf >=2.1.1,<3.0.0
    - parse >=1.19.0,<=2.0.0
    - pip-tools >=6.5,<8.0.0
    - pluggy >=1.0,<2.0
    - python >=3.7,<3.11
    - pyyaml >=4.2,<7.0
    - rich >=12.0,<14.0
    - rope >=1.4.0,<2.0
    - setuptools >=38.0,<70.0.0
    - toml >=0.10.0,<1.0.0
    - toposort >=1.5,<2.0

test:
  imports:
    - kedro
  commands:
    - kedro --help
# Disabled pip check because of pip-tools and rope
# pip requirements.txt is has requirement pip-tools~=6.10, but conda has only pip-tools 6.6.2
# pip requirements.txt is has requirement rope~=1.5.1, but conda has only rope 1.4.0.
#    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumblacklabs/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://kedro.readthedocs.io/
  dev_url: https://github.com/quantumblacklabs/kedro
  description: A Python framework for creating reproducible, maintainable and modular data science code.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - yetudada
    - idanov
    - merelcht
    - AhdraMeraliQB
    - NeroOkwa
    - noklam
    - SajidAlamQB
    - lrcouto
    - DimedS
