{% set name = "kedro" %}
{% set version = "0.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumblacklabs/kedro/archive/{{ version }}.tar.gz
  sha256: 61a66b6ca3b28d2c7cc870a86371d23bc0b14a21cece507ee21e6f87e2cb4b66

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kedro = kedro.cli:main

requirements:
  host:
    - pip
    - python >=3.6,<3.9
  run:
    - anyconfig <1.0,>=0.9.7
    - cachetools <5.0,>=4.1.0
    - click <8.0
    - cookiecutter <1.7.0,>=1.6.0
    - fsspec <0.7.0,>=0.5.1
    - jmespath <1.0,>=0.9.5
    - jupyter_client <6.0,>=5.1.0
    - pip-tools <6.0,>=5.0.0
    - pluggy <1.0.0,>=0.13.0
    - python >=3.6,<3.9
    - python-json-logger <1.0,>=0.1.9
    - pyyaml <6.0,>=4.2
    - toposort <2.0,>=1.5

test:
  imports:
    - kedro
  commands:
    - kedro --help

about:
  home: https://github.com/quantumblacklabs/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://kedro.readthedocs.io/
  dev_url: https://github.com/quantumblacklabs/kedro
  description: |
    Kedro is a development workflow framework that implements
    software engineering best-practice for data pipelines
    with an eye towards productionising machine learning models.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - lorenabalan
    - yetudada
    - idanov
