{% set name = "kedro" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumblacklabs/kedro/archive/{{ version }}.tar.gz
  sha256: 6cfc302dd48aa4ddc091e37f886b493afa87a25b07e6e0919a8f71351eb6cd06

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kedro = kedro.framework.cli:main

requirements:
  host:
    - pip
    - python >=3.6,<3.9
  run:
    - anyconfig >=0.10.0,<0.11.0
    - cachetools >=4.1,<5
    - click <8.0
    - cookiecutter >=1.7.0,<1.8.0
    - dynaconf <3.1.6,<4.0
    - fsspec >=2021.04,<2022.01
    - gitpython >=3.0,<4
    - jmespath >=0.9.5,<1.0
    - jupyter_client >=5.1,<7.0
    - pip-tools >=6.4,<7.0
    - pluggy >=0.13.0,<0.14.0
    - python >=3.6,<3.9
    - python-json-logger >=2.0.0,<3.0.0
    - pyyaml >=4.2,<6.0
    - rope >=0.21.0,<0.22.0
    - setuptools >=38.0
    - toml >=0.10,<0.11
    - toposort >=1.5,<2.0
    - git

test:
  imports:
    - kedro
  commands:
    - kedro --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumblacklabs/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://kedro.readthedocs.io/
  dev_url: https://github.com/quantumblacklabs/kedro
  description: |
    Kedro is a development workflow framework that implements
    software engineering best-practice for data pipelines
    with an eye towards productionising machine learning models.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - lorenabalan
    - yetudada
    - idanov
