{% set name = "kedro" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumblacklabs/kedro/archive/{{ version }}.tar.gz
  sha256: d3367da3fe7aa2fb4e403296f48fa317b53932674f81ebb52509bf3de6c503a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kedro = kedro.framework.cli:main

requirements:
  host:
    - pip
    - python >=3.6,<3.9
  run:
    - anyconfig >=0.9.7,<0.10
    - cachetools >=4.1,<5
    - click <8.0
    - cookiecutter >=1.6.0,<1.7.0
    - fsspec >=0.5.1,<0.7.0
    - jmespath >=0.9.5,<1.0
    - jupyter_client >=5.1,<6.0
    - pip-tools >=5.0,<6.0
    - pluggy >=0.13.0,<0.14.0
    - python >=3.6,<3.9
    - python-json-logger >=0.1.9,<0.2.0
    - pyyaml >=4.2,<6.0
    - setuptools >=38.0,<47.0
    - toposort >=1.5,<2.0
    - gitpython

test:
  imports:
    - kedro
  commands:
    - kedro --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumblacklabs/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://kedro.readthedocs.io/
  dev_url: https://github.com/quantumblacklabs/kedro
  description: |
    Kedro is a development workflow framework that implements
    software engineering best-practice for data pipelines
    with an eye towards productionising machine learning models.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - lorenabalan
    - yetudada
    - idanov
